### ISSUE TITLE
Using the CLIMATE_FAN_QUIET instead of DIFFUSE

### ISSUE THREAD

**Issue by Bill-Dung** [Bill-Dung/MHI-AC-Ctrl-ESPHome#1]
[ervee](https://github.com/ervee) commented
[Perhaps using the CLIMATE_FAN_QUIET instead of DIFFUSE. CLIMATE_FAN_QUIET should also be available in climate and esphome and is perhaps a more logical choice for ultra-low fan speed.](https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/issues/51#issuecomment-1456546983)

CLIMATE_FAN_QUIET is not be showing up in Home Assistant Card like CLIMATE_FAN_MIDDLE and CLIMATE_FAN_FOCUS.

I already opened a feature request at ESPHome: https://github.com/esphome/feature-requests/issues/2149

**Comment by ervee** [comment]
I think that would be a breaking change at Esphome if you were to insert a new value bumping the other +1.
I wonder why Quiet is not available in the climate card.

**Comment by RobertJansen1** [comment]
Wouldn't it be better to use the CLIMATE_FAN_QUIET which is already there, and update HomeAssistant add quiet?

**Comment by RobertJansen1** [comment]
oh, i think it now is in home assistant:

https://github.com/home-assistant/core/commit/d14000f7049f955a08b9c164798f5f78335e54b6

**Comment by Bill-Dung** [comment]
Everything's done for me
